# Generated by Django 3.2.9 on 2021-12-10 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwardsapp', '0003_auto_20211210_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
