# Generated by Django 3.2.9 on 2021-12-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwardsapp', '0004_alter_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=300),
        ),
    ]
