# Generated by Django 3.2.9 on 2021-12-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwardsapp', '0006_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
