# Generated by Django 3.2.9 on 2021-12-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwwardsapp', '0008_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='avg_rate',
            new_name='avarage_rate',
        ),
    ]
