# Generated by Django 3.2.9 on 2021-12-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('awwwardsapp', '0009_rename_avg_rate_rating_avarage_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.CharField(default='Kenya', max_length=50),
        ),
    ]
